services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - .:/app

volumes:
  mongo_data: